
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  PrismaClientKnownRequestError,
  PrismaClientUnknownRequestError,
  PrismaClientRustPanicError,
  PrismaClientInitializationError,
  PrismaClientValidationError,
  getPrismaClient,
  sqltag,
  empty,
  join,
  raw,
  skip,
  Decimal,
  Debug,
  objectEnumValues,
  makeStrictEnum,
  Extensions,
  warnOnce,
  defineDmmfProperty,
  Public,
  getRuntime,
  createParam,
} = require('./runtime/wasm-engine-edge.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = PrismaClientKnownRequestError;
Prisma.PrismaClientUnknownRequestError = PrismaClientUnknownRequestError
Prisma.PrismaClientRustPanicError = PrismaClientRustPanicError
Prisma.PrismaClientInitializationError = PrismaClientInitializationError
Prisma.PrismaClientValidationError = PrismaClientValidationError
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = sqltag
Prisma.empty = empty
Prisma.join = join
Prisma.raw = raw
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = Extensions.getExtensionContext
Prisma.defineExtension = Extensions.defineExtension

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}





/**
 * Enums
 */
exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.ClubSyncSnapshotScalarFieldEnum = {
  id: 'id',
  clubId: 'clubId',
  tables: 'tables',
  revenue: 'revenue',
  syncedAt: 'syncedAt'
};

exports.Prisma.ClubSessionRecordScalarFieldEnum = {
  id: 'id',
  clubId: 'clubId',
  externalId: 'externalId',
  tableId: 'tableId',
  tableName: 'tableName',
  mode: 'mode',
  startTime: 'startTime',
  endTime: 'endTime',
  duration: 'duration',
  tableCost: 'tableCost',
  barCost: 'barCost',
  totalCost: 'totalCost',
  date: 'date',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};


exports.Prisma.ModelName = {
  ClubSyncSnapshot: 'ClubSyncSnapshot',
  ClubSessionRecord: 'ClubSessionRecord'
};
/**
 * Create the Client
 */
const config = {
  "generator": {
    "name": "client",
    "provider": {
      "fromEnvVar": null,
      "value": "prisma-client-js"
    },
    "output": {
      "value": "/Users/samandarlev/Desktop/biliardo-site/services/club/src/_prisma",
      "fromEnvVar": null
    },
    "config": {
      "engineType": "library"
    },
    "binaryTargets": [
      {
        "fromEnvVar": null,
        "value": "darwin-arm64",
        "native": true
      }
    ],
    "previewFeatures": [],
    "sourceFilePath": "/Users/samandarlev/Desktop/biliardo-site/services/club/prisma/schema.prisma",
    "isCustomOutput": true
  },
  "relativeEnvPaths": {
    "rootEnvPath": null,
    "schemaEnvPath": "../../.env"
  },
  "relativePath": "../../prisma",
  "clientVersion": "6.19.3",
  "engineVersion": "c2990dca591cba766e3b7ef5d9e8a84796e47ab7",
  "datasourceNames": [
    "db"
  ],
  "activeProvider": "postgresql",
  "inlineDatasources": {
    "db": {
      "url": {
        "fromEnvVar": "DATABASE_URL",
        "value": null
      }
    }
  },
  "inlineSchema": "// Club-сервис: владеет схемой `club`.\n// Хранит снимки состояния клуба (один на клуб, перезаписывается при каждом SYNC)\n// и историю завершённых сессий (idempotent по externalId).\n// userId/clubId — opaque-строки, FK на чужие схемы не используем.\n\ngenerator client {\n  provider = \"prisma-client-js\"\n  output   = \"../src/_prisma\"\n}\n\ndatasource db {\n  provider = \"postgresql\"\n  url      = env(\"DATABASE_URL\")\n  schemas  = [\"club\"]\n}\n\n/// Последний снимок состояния клуба. Один на клуб, перезаписывается при каждом SYNC.\nmodel ClubSyncSnapshot {\n  id       String   @id @default(cuid())\n  clubId   String   @unique // user.id из auth-схемы (opaque)\n  /// JSON: TableSnapshot[] (см. shared types)\n  tables   Json\n  /// JSON: { table, bar, total, sessionsCount }\n  revenue  Json\n  syncedAt DateTime @default(now())\n\n  @@schema(\"club\")\n}\n\n/// История завершённых сессий, присланных desktop-приложением.\n/// externalId уникален в пределах clubId — повторный sync не дублирует.\nmodel ClubSessionRecord {\n  id         String   @id @default(cuid())\n  clubId     String\n  externalId String\n  tableId    Int\n  tableName  String\n  mode       String\n  startTime  DateTime\n  endTime    DateTime\n  /// Минуты\n  duration   Int\n  /// Тенге\n  tableCost  Int\n  barCost    Int\n  totalCost  Int\n  /// \"YYYY-MM-DD\" — для быстрой группировки в отчётах\n  date       String\n  createdAt  DateTime @default(now())\n\n  @@unique([clubId, externalId])\n  @@index([clubId, date])\n  @@index([clubId, startTime])\n  @@schema(\"club\")\n}\n",
  "inlineSchemaHash": "d4f893d74dd14cafff808f8828989048dfb63e4e8f14cf6b9760b1424c038921",
  "copyEngine": true
}
config.dirname = '/'

config.runtimeDataModel = JSON.parse("{\"models\":{\"ClubSyncSnapshot\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"clubId\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"tables\",\"kind\":\"scalar\",\"type\":\"Json\"},{\"name\":\"revenue\",\"kind\":\"scalar\",\"type\":\"Json\"},{\"name\":\"syncedAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"}],\"dbName\":null},\"ClubSessionRecord\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"clubId\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"externalId\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"tableId\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"tableName\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"mode\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"startTime\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"endTime\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"duration\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"tableCost\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"barCost\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"totalCost\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"date\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"createdAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"}],\"dbName\":null}},\"enums\":{},\"types\":{}}")
defineDmmfProperty(exports.Prisma, config.runtimeDataModel)
config.engineWasm = {
  getRuntime: async () => require('./query_engine_bg.js'),
  getQueryEngineWasmModule: async () => {
    const loader = (await import('#wasm-engine-loader')).default
    const engine = (await loader).default
    return engine
  }
}
config.compilerWasm = undefined

config.injectableEdgeEnv = () => ({
  parsed: {
    DATABASE_URL: typeof globalThis !== 'undefined' && globalThis['DATABASE_URL'] || typeof process !== 'undefined' && process.env && process.env.DATABASE_URL || undefined
  }
})

if (typeof globalThis !== 'undefined' && globalThis['DEBUG'] || typeof process !== 'undefined' && process.env && process.env.DEBUG || undefined) {
  Debug.enable(typeof globalThis !== 'undefined' && globalThis['DEBUG'] || typeof process !== 'undefined' && process.env && process.env.DEBUG || undefined)
}

const PrismaClient = getPrismaClient(config)
exports.PrismaClient = PrismaClient
Object.assign(exports, Prisma)

